### ISSUE TITLE
[9.0] Handling of payment/direct debit orders (SEPA, DTA...)

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/account-payment#68]
I have created this issue to track all the discussion around how to handle payment/direct debit orders in Odoo 9.0.

In a nutshell:
- Odoo has removed _account_voucher_ and _account_payment_ modules in version 9.
- There's a new object account.payment for handling all.
- There is an enterprise module that allows to make SEPA payment orders (SEPA credit transfer, not SEPA direct debit).

@fclementic2c made this document summarizing well the situation and with a proposal: https://docs.google.com/document/d/1FfaitydiW5uFjyIwtMT9fVbScwBefCATmoM2x7HNVbk/edit#. At the end, he proposes to extend the current `account.payment` model to fit the rest of the needs, but having studied the v9 code, I don't agree.

Trying to fit our needs/features inside a model that has some wrong base concepts (be based on invoices instead of journal entries, strange workflow for following the payment...) will make us to work a lot to make it, inhibit a lot of things, hack other, and all of this to be repeated on each version. I see also no real advantage of doing that, because there are very few possible integrations that we can use extending the object.

A new object will allow us to keep a clean base code that avoids to make ugly hacks like in the past, and also to control all the data model without depending on Odoo changes.

Besides, using a new object doesn't prevent to integrate with the new cool features that v9 brings. For example, the payments widget on the bottom of the invoice:

![seleccion_003](https://cloud.githubusercontent.com/assets/7165771/13993238/ccaebb44-f11f-11e5-9523-ef05148c9f35.png)

We will only need to extend the method https://github.com/odoo/odoo/blob/7682760dcad232829fbb5d4221f66a1ebb9d6c91/addons/account/models/account_invoice.py#L142

The new object I'm proposing is to take again the v9 `payment.order` model, and rename it to `account.payment.order` to fit current naming conventions, but with all the logic we have already built for v8 and before.

So, my proposal is:
- Take Odoo's v8 _account_payment_ module and ported to v9 in new API, calling it _account_payment_order_.
- Merge _account_baking_payment_export_ module in this one.
- Put this module in OCA/account-payment repository.
- Export all the SEPA/DTA modules without too much changes (only the model renaming).
- These modules can still live in OCA/bank-payment repository, because it makes sense to be there.
- Add some features like the integration with the payment widget info in the module set (probably in the set).

What do you think?

**Comment by pedrobaeza** [comment]
cc @yvaucher @BT-astauder @BT-mtallon @jbeficent @fclementic2c, you will be interested in this.

**Comment by fclementic2c** [comment]
Thanks for your analysis @pedrobaeza . 
I agree with you :)

Here are few very importants points/remarks I think:
- This new payment order **must post payment entries at the payment order closing** (last status). So no more import in the bank statement obviously 
- have a clear workflow : Draft, Open (here you can import account move lines and generate xml file as many times as wanted), closed (can be re-open with Financial manager rights) - I am not sure if it currently works this way but I remember that I had many problems with this workflow in the past.
- Since w do not display supplier invoices/credit notes we must have a improved view of move lines :  (see the attached file payment_view.xml) to ease the selection of amount to be paid, handle partial payment and multi-currency : 
  [payment_view.xml.zip](https://github.com/OCA/account-payment/files/187416/payment_view.xml.zip)
- We must handle different version to handle SEPA v03, v04, v05, SEPA-CH for example. But I guess this is part of port of current branch.

thanks

**Comment by BT-fgarbely** [comment]
Hello everybody

Just for your information:
I start with the merge of _account_banking_payment_export_ into _account_payment_order_.

Regards

**Comment by pedrobaeza** [comment]
Great, @BT-fgarbely, let me know if you have any doubt. I assign you in https://github.com/OCA/bank-payment/issues/222

**Comment by JordiBForgeFlow** [comment]
The proposal from Pedro makes sense to me. 

In this scenario the new account.payment object would have more limited functionality, similar to the account.voucher in v8. But still, that is very useful for companies that wish to record immediately the payment of an invoice, and not really dealing with automated bank transfers. And there's a lot of them, based on my experience. The usability improvements are good.

In my opinion, the proposed new account.payment.order should be used as it is in v8, but should coexist with the payment.order model.

Companies wishing to use both models should set-up the payment.order to post payments to a waiting payments account, if they wish to flag invoices as paid when they do the payment, and if these  payments are to be communicated to the bank using an account.payment.order. 

Then, the account.payment.order should be able to select unreconciled entries from the waiting payments. If the company did not want to manually pay the invoices, the account.payment.order should allow them to manually select accounts receivable / accounts payable unreconciled items as well. 

Then, the account.payment.order would be processed and monitored until it is concluded. If the payment was done from a waiting account, it would move from waiting account to the final bank account when the payment order is completed.

In v8 I would normally do the exact same thing, but using account.voucher instead of payment.order!

**Comment by nmoturi** [comment]
I would also like to suggest to have account.payment.order have an option to select the credit notes (refunds) as well if we are giving a option to mark invoices as paid. In a typical supplier payment management I haven't come across any customer ( at least in Australia) to process individual invoices other than service based invoices. They would like to have one interface like a payment run - to select the outstanding invoices with the option to select refunds and the net amount is generated in an EFT file to upload into bank for payment. All the invoices along with the refunds are reconciled once the payment order is flagged as done. We have enhanced quite a lot in Payment order to achieve the same, but in V7.

**Comment by pedrobaeza** [comment]
@nmoturi, last version of v8 _account_banking_payment_export_ is able to handle this. Have you tried?

**Comment by nmoturi** [comment]
Thank's Pedro. No, I haven't tried v8 module and glad to know this has been already covered.

**Comment by stephankeller** [comment]
I just want to add that in the US, probably all our customers register the payments from invoices that is the main way to enter payments.

**Comment by yvaucher** [comment]
@alexis-via I heard you will work on SEPA payment during Sorento code sprint, keep us posted if you do anything on restoring payment order.

Please note also that there is a version of a payment order (Payment Register) in https://github.com/OCA/l10n-switzerland/pull/212 done by @BT-mtallon , thought you might want something a bit more generic.

**Comment by pedrobaeza** [comment]
@alexis-via, you would be the ideal person to work on this as you already worked with this set of modules before. Please check https://github.com/pedrobaeza/account-payment/tree/9.0-account_payment_order that is the start of the merge work. I have moved them to account-payment because it makes more sense as you can have payment orders without involving the bank activity, and thus we will have each thing in its corresponding place.

Don't hesitate to contact me for any question or for working remotely with you in this.

**Comment by yvaucher** [comment]
@alexis-via And have fun at Sorrento :smile:

**Comment by alexis-via** [comment]
This is gonna be a 2nd revolution in OCA/bank-payment ! Many great things are coming !

**Comment by alexis-via** [comment]
in v8, account_payment_partner depends on account_banking_payment_export.

In v9, we would like to do the contrary : account_payment_order (which replaces account_payment and account_banking_payment_export) will depend on account_payment_partner. In fact, the dependancy would be the following:

account_payment_order -> account_payment_partner -> account_payment_mode

This will allow the e-commerce modules (such as sale_payment_method) to use account_payment_mode + account_payment_partner + account_payment_sale without depending on account_payment_order.

If you have projects where you use payment orders but you don't want to install account_payment_partner, please yell now and give a good reason. Tomorrow morning, it will be too late :)

This change has already been approved by @sbidoul, @sebastienbeau and me.

**Comment by yvaucher** [comment]
To reference it: OCA/bank-payment#270

**Comment by yvaucher** [comment]
By the way shouldn't account_payment_order module be in OCA/account-payment repository ?

**Comment by pedrobaeza** [comment]
It was decided in the Sorrento code sprint to keep it in the same branch for not "disturbing" users that are used to go to this branch.

**Comment by pedrobaeza** [comment]
Closing as this was handled so long ago.
